apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
# spec:
#   selector: 
#     app: alertmanager
#   type: NodePort  
#   ports:
#     - port: 9093
#       targetPort: 9093
#       nodePort: 31000
      
      
spec:
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
  sessionAffinity: None
  type: LoadBalancer
    
    
