apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  labels:
    vol: alertmanager-storage
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi